### ISSUE TITLE
your mom requires stupid.rb but isn't shipped in gem

### ISSUE THREAD

**Issue by stahnma** [adambair/your_mom#3]
your mom requires stupid.rb but isn't shipped in gem.  

While your mom offers an array of other services, functionality in ruby apparently isn't one of them....

**Comment by adambair** [comment]
OH NOES! I'll get right on that ;)

**Comment by adambair** [comment]
Also, lol re: services.

**Comment by adambair** [comment]
That's odd. Stupid isn't actually in the project. Not even sure why I did that. Hahaha.

**Comment by adambair** [comment]
Fixed stupid. Added Ruby functionality. Pushed new gem and version. Fixed in v0.2.0. Your mom has been serviced.

**Comment by stahnma** [comment]
Thanks for getting on your_mom; I mean I know everybody else has, but when you did it results appeared.

**Comment by fowkswe** [comment]
I forked `your_mom` on github

**Comment by RudyOnRails** [comment]
I forked `your_mom` on Valentine's Day.
